### ISSUE TITLE
Action configuration - conflicting options (mode mouse vs stick left/right/....)

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/FLipMouse-esp32#2]
It is possible to set mouth stick actions, even if configured in mouse mode.

Suggestion:

Hide corresponding actions in `currentConfigTb` and `selectActionButton`

**Comment by klues** [comment]
fixed with https://github.com/asterics/FLipMouse-esp32/commit/a91816a5ec46127453bd9e155c6fc27da2326db2
also see here: https://asterics.github.io/FLipMouse-esp32/index.htm#tabActions

btw, funny: you and chris found this issue nearly at the same time - see his mail ;)
