### ISSUE TITLE
Compabibility for browsers that do not support ES2015

### ISSUE THREAD

**Issue by klues** [asterics/FLipMouse-esp32#6]
The web configuration page uses Javascript `Promises`. Nearly all latest browsers support them:
https://caniuse.com/#feat=promises

However some old devices (like my Asus TF101 with Android 4) with old browsers do not.
Maybe its ok to not support them, otherwise we have to recompile the JS with tools like https://babeljs.io/

**Comment by benjaminaigner** [comment]
Good point...
Do you have experience with babeljs?
Would be interesting how the backwards compatibility will affect the file size.

**Comment by klues** [comment]
Nowadays, after some more experience I wouldn't recommend `babeljs` anymore for this project because it would be an overkill. I think there are two reasons why this webapp doesn't run on old browsers:
1. usage of ES6 syntax like arrow functions (e.g. `list.filter(e => e.value === 1)`)
2. usage of Promises

(1) could be simply fixed manually by just searching for `=>` and replace it with `function`, so e.g. `list.filter(function(e) {return e.value === 1})`
(2) could be fixed by a Promise polyfill, e.g. https://github.com/stefanpenner/es6-promise

But I don't know if all of this is necessary. Currently on desktop the only non-supported browser is Internet Explorer and all current mobile browsers should be supported.
According to [caniuse - arrow functions](https://caniuse.com/#feat=arrow-functions) and [caniuse - Promises](https://caniuse.com/#feat=promises) about 97% of mobile users and 95% of desktop users are currently supported, so I think we could also just close this issue ;)

**Comment by benjaminaigner** [comment]
I think 95% are sufficient :-),
especially because:
-) we will provide an electron version
-) the WebGUI is used for configuration only (if the person does not have a new device, there should be an alternative around)
